apiVersion: v1
kind: Secret
metadata:
  name: {{ include "npb.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "npb.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: {{ .Values.secrets.POSTGRES_DB }}
  SECRET: {{ .Values.secrets.SECRET }}
